"""Init

Revision ID: 651612d9d629
Revises: 986455547bfb
Create Date: 2023-11-05 21:22:00.342039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "651612d9d629"
down_revision: Union[str, None] = "986455547bfb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contacts",
        "born_date",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.TIMESTAMP(timezone=False),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contacts",
        "born_date",
        existing_type=sa.DateTime(),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
